name: Cloudflare Workers Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - worker/**
      - .github/workflows/deploy-worker.yml

defaults:
  run:
    working-directory: worker

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '${{ github.workspace }}/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Install latest Wrangler
        run: |
          npm install -g wrangler@latest
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.MASK_WORKER_URL }}"
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "worker"
          command: deploy
          secrets: |
            SUPABASE_URL
            SUPABASE_API_KEY
            SUPABASE_JWT_SECRET
            SUPAFLARE_ADMIN_KEY
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
          SUPAFLARE_ADMIN_KEY: ${{ secrets.SUPAFLARE_ADMIN_KEY }}
